name:                tiger-compiler
version:             0.1.0.0
github:              "tkclimb/tiger-compiler"
license:             BSD3
author:              "tkclimb"
maintainer:          "tkclimb0911@gmail.com"
copyright:           "2019 tkclimb"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tkclimb/tiger-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- text

library:
  source-dirs: src

executables:
  tiger-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tiger-compiler

tests:
  tiger-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tiger-compiler
